CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "TRegistered" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"sTitle"	TEXT NOT NULL,
	"sPhoto"	TEXT,
	"sWhere"	TEXT,
	"sContact"	TEXT,
	"dInserted"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "TRequested" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"sTitle"	TEXT NOT NULL,
	"sPhoto"	TEXT,
	"sWhere"	TEXT,
	"sContact"	TEXT,
	"dInserted"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
